# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'change_password.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(247, 248)
        self.btn = QtWidgets.QPushButton(Dialog)
        self.btn.setGeometry(QtCore.QRect(62, 122, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn.setFont(font)
        self.btn.setObjectName("btn")
        self.old_password = QtWidgets.QLineEdit(Dialog)
        self.old_password.setGeometry(QtCore.QRect(62, 26, 131, 31))
        self.old_password.setObjectName("old_password")
        self.new_password = QtWidgets.QLineEdit(Dialog)
        self.new_password.setGeometry(QtCore.QRect(62, 85, 131, 31))
        self.new_password.setObjectName("new_password")
        self.error = QtWidgets.QLabel(Dialog)
        self.error.setGeometry(QtCore.QRect(0, 170, 241, 71))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.error.setFont(font)
        self.error.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.error.setStyleSheet("color:red; \n"
"text-align: center;")
        self.error.setText("")
        self.error.setAlignment(QtCore.Qt.AlignCenter)
        self.error.setObjectName("error")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 5, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(60, 60, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Change password"))
        self.btn.setText(_translate("Dialog", "Confirm"))
        self.label.setText(_translate("Dialog", "current password"))
        self.label_2.setText(_translate("Dialog", "new password"))
