# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'info.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dsad(object):
    def setupUi(self, dsad):
        dsad.setObjectName("dsad")
        dsad.resize(271, 175)
        self.dsad_2 = QtWidgets.QLabel(dsad)
        self.dsad_2.setGeometry(QtCore.QRect(10, 30, 251, 91))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dsad_2.setFont(font)
        self.dsad_2.setTextFormat(QtCore.Qt.PlainText)
        self.dsad_2.setObjectName("dsad_2")

        self.retranslateUi(dsad)
        QtCore.QMetaObject.connectSlotsByName(dsad)

    def retranslateUi(self, dsad):
        _translate = QtCore.QCoreApplication.translate
        dsad.setWindowTitle(_translate("dsad", "Dialog"))
        self.dsad_2.setText(_translate("dsad", "Сендецький Костянтин ФБ-96 \n"
"\n"
"6. Наявність латинських букв, \n"
"символів кирилиці і цифр"))
